name: Glog Scan (dev)
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  glog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout glog-action repository
        uses: actions/checkout@v4
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/glog-action
          ref: main

      - name: Run Glog.AI
        uses: ./.github/glog-action
        with:
          client: 'test'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
          upload: 'false'
          on-prem-upload: 'true'
          issue: 'false'
          autofix: 'false'
          sarif-format-type: 'STANDARD'
          sbom: 'true'
          env: 'dev'
          scl-uuid: 'aceb1da1-ab34-455b-baa1-d6d44f335fb5'
          dev: 'true'

